// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKzmuLKc9z9hUke6qNJ5ts76kOJrJpFRU',
    appId: '1:243492492145:web:1d5c0a10af95528c159cd0',
    messagingSenderId: '243492492145',
    projectId: 'director-2024-redencion',
    authDomain: 'director-2024-redencion.firebaseapp.com',
    storageBucket: 'director-2024-redencion.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzV_qaDuCXyV9H5ua23xU2HPY8FGSco2M',
    appId: '1:243492492145:android:4a5ab9f04df1ed06159cd0',
    messagingSenderId: '243492492145',
    projectId: 'director-2024-redencion',
    storageBucket: 'director-2024-redencion.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcTsvq5koO8VfDOOymtOs68a0f4Znj7bw',
    appId: '1:243492492145:ios:c3e490d6cf18c489159cd0',
    messagingSenderId: '243492492145',
    projectId: 'director-2024-redencion',
    storageBucket: 'director-2024-redencion.appspot.com',
    androidClientId: '243492492145-71ioshos8e947guonpa88iplktf9ve6p.apps.googleusercontent.com',
    iosClientId: '243492492145-vqs707s59ojk8p8pft06auc32klilmqf.apps.googleusercontent.com',
    iosBundleId: 'com.example.directorAppTfg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcTsvq5koO8VfDOOymtOs68a0f4Znj7bw',
    appId: '1:243492492145:ios:783933693ef94bc2159cd0',
    messagingSenderId: '243492492145',
    projectId: 'director-2024-redencion',
    storageBucket: 'director-2024-redencion.appspot.com',
    androidClientId: '243492492145-71ioshos8e947guonpa88iplktf9ve6p.apps.googleusercontent.com',
    iosClientId: '243492492145-ncfvsahj8fvl5fksnq0nucd6dclbbfi2.apps.googleusercontent.com',
    iosBundleId: 'com.example.directorAppTfg.RunnerTests',
  );
}
